name: build
on:
  push:
    branches:
     - "*"
  pull_request:
    branches:
      - "master"
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore
        run: nuget restore ./src
      - name: Build
        run: msbuild ./src/AppPoolMonitor.sln
